<<<<<<< HEAD
version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: fintech-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    container_name: fintech-api-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data:
=======
version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: fintech-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    container_name: fintech-api-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data:
>>>>>>> 4ffa9561589c88bb39f5fc3ae2d42d159543398b
