# Server
server.port=8080

# Database (PostgreSQL)
# spring.datasource.url=jdbc:postgresql://localhost:5432/fintech_db
spring.datasource.url=jdbc:postgresql://db:5432/fintech_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=fintech123

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=fintechSuperSecretKey123456789012345678901234567890
app.jwt.expiration-ms=86400000

# App
app.name=Fintech API
logging.level.com.fintech=DEBUG
